// 365-Day Field Medicine Curriculum
// Each lesson has: day, module, title, objective, topic area

export const MODULES = [
  { id: 'foundations',    name: 'Field Medicine Foundations',   icon: '🏕️', color: '#8B6914', days: '1-30' },
  { id: 'wounds',         name: 'Wounds & Bleeding Control',    icon: '🩹', color: '#B94040', days: '31-60' },
  { id: 'bones',          name: 'Bones, Joints & Trauma',       icon: '🦴', color: '#6B8C42', days: '61-90' },
  { id: 'environment',    name: 'Environmental Emergencies',    icon: '🌡️', color: '#2E7D8C', days: '91-130' },
  { id: 'navigation',     name: 'Navigation & Rescue Signals',  icon: '🧭', color: '#5C4A8C', days: '131-160' },
  { id: 'survival',       name: 'Wilderness Survival Skills',   icon: '🔥', color: '#C46A00', days: '161-200' },
  { id: 'pediatric',      name: 'Kid-Specific First Aid',       icon: '👧', color: '#D4548A', days: '201-240' },
  { id: 'plants',         name: 'Plants, Animals & Toxins',     icon: '🐍', color: '#4A7C4E', days: '241-280' },
  { id: 'systems',        name: 'Body Systems & Illness',       icon: '🫀', color: '#8C3A3A', days: '281-320' },
  { id: 'mastery',        name: 'Scenarios & Mastery',          icon: '⭐', color: '#7A6400', days: '321-365' },
];

export const BADGES = [
  { id: 'first_step',    name: 'First Step',        icon: '👣', desc: 'Complete your first lesson',          req: d => d >= 1 },
  { id: 'week_one',      name: 'Trail Ready',       icon: '🥾', desc: 'Complete 7 days',                     req: d => d >= 7 },
  { id: 'streak_14',     name: 'Consistent',        icon: '🔥', desc: '14-day streak',                       req: (d, s) => s >= 14 },
  { id: 'month_one',     name: 'Field Apprentice',  icon: '🏕️', desc: 'Complete 30 days',                   req: d => d >= 30 },
  { id: 'wounds_done',   name: 'Wound Warrior',     icon: '🩹', desc: 'Finish Wounds module',                req: d => d >= 60 },
  { id: 'bones_done',    name: 'Bone Doc',          icon: '🦴', desc: 'Finish Bones & Trauma module',        req: d => d >= 90 },
  { id: 'env_done',      name: 'Weather Watcher',   icon: '🌡️', desc: 'Finish Environmental module',        req: d => d >= 130 },
  { id: 'halfway',       name: 'Halfway Hero',      icon: '🏔️', desc: 'Complete 182 days',                  req: d => d >= 182 },
  { id: 'kid_done',      name: 'Parent Medic',      icon: '👧', desc: 'Finish Kid-Specific module',          req: d => d >= 240 },
  { id: 'streak_30',     name: 'Relentless',        icon: '⚡', desc: '30-day streak',                       req: (d, s) => s >= 30 },
  { id: 'day_300',       name: 'Field Surgeon',     icon: '🩺', desc: 'Complete 300 days',                   req: d => d >= 300 },
  { id: 'graduate',      name: 'Field Medic',       icon: '⭐', desc: 'Complete all 365 days',               req: d => d >= 365 },
];

export const XP_PER_LESSON = 100;
export const STREAK_BONUS = 25; // extra XP per lesson when on streak ≥ 3

export function getLevel(xp) {
  const levels = [
    { level: 1,  name: 'Hiker',           minXp: 0 },
    { level: 2,  name: 'Trail Scout',     minXp: 500 },
    { level: 3,  name: 'Camp Medic',      minXp: 1500 },
    { level: 4,  name: 'Field Responder', minXp: 3000 },
    { level: 5,  name: 'Wilderness EMT',  minXp: 6000 },
    { level: 6,  name: 'Trail Doctor',    minXp: 12000 },
    { level: 7,  name: 'Field Surgeon',   minXp: 20000 },
    { level: 8,  name: 'Expedition Lead', minXp: 30000 },
  ];
  for (let i = levels.length - 1; i >= 0; i--) {
    if (xp >= levels[i].minXp) return { ...levels[i], next: levels[i + 1] || null };
  }
  return levels[0];
}

export function getModuleForDay(day) {
  if (day <= 30)  return MODULES[0];
  if (day <= 60)  return MODULES[1];
  if (day <= 90)  return MODULES[2];
  if (day <= 130) return MODULES[3];
  if (day <= 160) return MODULES[4];
  if (day <= 200) return MODULES[5];
  if (day <= 240) return MODULES[6];
  if (day <= 280) return MODULES[7];
  if (day <= 320) return MODULES[8];
  return MODULES[9];
}

// Structured lesson titles for all 365 days
export const LESSON_TITLES = {
  // Module 1: Foundations (1-30)
  1:  { title: 'The Wilderness Mindset',              topic: 'Scene safety, Stay Calm, Act Fast' },
  2:  { title: 'Your First Aid Kit Essentials',       topic: 'What to carry camping with kids' },
  3:  { title: 'The ABCs of Emergency Response',      topic: 'Airway, Breathing, Circulation' },
  4:  { title: 'Patient Assessment: Step One',        topic: 'Scene size-up and initial impression' },
  5:  { title: 'Vital Signs: Pulse Check',            topic: 'Finding and counting a pulse' },
  6:  { title: 'Vital Signs: Breathing Rate',         topic: 'Normal vs abnormal breathing' },
  7:  { title: 'Vital Signs: Skin Signs',             topic: 'Color, temperature, moisture' },
  8:  { title: 'Level of Consciousness (AVPU)',       topic: 'Alert, Voice, Pain, Unresponsive scale' },
  9:  { title: 'SAMPLE History Taking',               topic: 'Signs, Allergies, Meds, Past, Last, Events' },
  10: { title: 'How to Call for Help',                topic: 'Cell, satellite messenger, whistle signals' },
  11: { title: 'The Golden Hour Principle',           topic: 'Time-critical injuries in the backcountry' },
  12: { title: 'Improvised Stretchers',               topic: 'Moving an injured person safely' },
  13: { title: 'Universal Precautions',               topic: 'Gloves, barriers, preventing infection' },
  14: { title: 'Consent and Good Samaritan Laws',     topic: 'Legal basics of helping someone' },
  15: { title: 'Documentation in the Field',          topic: 'Keeping notes on an injured person' },
  16: { title: 'Stress and Decision Making',          topic: 'Managing panic in an emergency' },
  17: { title: 'Communication Under Pressure',        topic: 'Delegating, staying clear-headed' },
  18: { title: 'The STOP Principle',                  topic: 'Stop, Think, Observe, Plan' },
  19: { title: 'Prioritizing Multiple Casualties',    topic: 'Basic field triage concepts' },
  20: { title: 'Emergency Evacuation Basics',         topic: 'When to stay put vs. evacuate' },
  21: { title: 'Night Emergencies',                   topic: 'Working with limited visibility' },
  22: { title: 'Weather Reading for Safety',          topic: 'Clouds, wind, lightning signs' },
  23: { title: 'Your Body\'s Emergency Response',     topic: 'Adrenaline, shock response physiology' },
  24: { title: 'Infection: The Silent Threat',        topic: 'Recognizing and preventing infection' },
  25: { title: 'Pain Assessment in the Field',        topic: 'OPQRST framework' },
  26: { title: 'Building a Field First Aid Kit',      topic: 'DIY kit for hiking with kids' },
  27: { title: 'Medication Basics for Hikers',        topic: 'OTC meds to carry, dosing basics' },
  28: { title: 'Anatomy Overview: Trunk & Spine',     topic: 'Organs, ribs, pelvis landmarks' },
  29: { title: 'Anatomy Overview: Extremities',       topic: 'Bones, major vessels, nerve paths' },
  30: { title: 'Module 1 Review: Scenario Drill',     topic: 'Put it all together — trail accident sim' },

  // Module 2: Wounds & Bleeding (31-60)
  31: { title: 'Skin: Your Biggest Organ',            topic: 'Layers, functions, and wound types' },
  32: { title: 'Arterial vs Venous Bleeding',         topic: 'Bright spurting vs dark slow flow' },
  33: { title: 'Direct Pressure: The First Step',     topic: 'Technique, time, and pressure points' },
  34: { title: 'Tourniquets in the Backcountry',      topic: 'When and how to apply' },
  35: { title: 'Packing a Wound',                     topic: 'Wound packing technique with gauze' },
  36: { title: 'Pressure Bandaging',                  topic: 'Israeli bandage and improvised versions' },
  37: { title: 'Wound Irrigation',                    topic: 'Cleaning wounds with water pressure' },
  38: { title: 'Wound Closure Strips',                topic: 'Steri-strips, butterfly closures' },
  39: { title: 'Abrasions and Road Rash',             topic: 'Cleaning, dressing, kids & gravel' },
  40: { title: 'Lacerations: To Close or Not',        topic: 'Criteria for field closure' },
  41: { title: 'Puncture Wounds',                     topic: 'Sticks, rocks, nails — special risks' },
  42: { title: 'Impaled Objects',                     topic: 'Never remove — stabilize in place' },
  43: { title: 'Avulsions and Degloving',             topic: 'When skin is torn away' },
  44: { title: 'Head Wounds: High Bleeders',          topic: 'Why scalp wounds look scarier than they are' },
  45: { title: 'Internal Bleeding Signs',             topic: 'Hidden bleeding you can\'t see' },
  46: { title: 'Chest Wounds',                        topic: 'Sucking chest wounds, sealing them' },
  47: { title: 'Abdominal Wounds',                    topic: 'Evisceration, covering, positioning' },
  48: { title: 'Hemostatic Agents',                   topic: 'QuikClot, Combat Gauze basics' },
  49: { title: 'Blisters: Prevention and Treatment',  topic: 'Moleskin, draining, covering' },
  50: { title: 'Burns: Classification',               topic: 'First, second, third degree burns' },
  51: { title: 'Burns: Field Treatment',              topic: 'Cool water, cover, no butter' },
  52: { title: 'Sunburn Management',                  topic: 'Kids and UV damage, treatment' },
  53: { title: 'Infected Wounds: Warning Signs',      topic: 'Redness, warmth, pus, red streaks' },
  54: { title: 'Wound Dressing Changes',              topic: 'How often and how to rewrap' },
  55: { title: 'Improvised Bandages',                 topic: 'T-shirts, bandanas, duct tape hacks' },
  56: { title: 'Nosebleeds',                          topic: 'Pinch, lean forward, 10 minutes' },
  57: { title: 'Eye Injuries',                        topic: 'Foreign bodies, chemical splash, trauma' },
  58: { title: 'Tooth Injuries',                      topic: 'Knocked out tooth — milk trick' },
  59: { title: 'Ear and Nose Foreign Bodies',         topic: 'Kids putting things where they shouldn\'t' },
  60: { title: 'Module 2 Review: Bleeding Scenarios', topic: 'Compound scenario, trail accident' },

  // Module 3: Bones, Joints & Trauma (61-90)
  61: { title: 'Bone Anatomy Basics',                 topic: 'Types of bones, fracture types' },
  62: { title: 'Recognizing a Fracture',              topic: 'DOTS: Deformity, Open, Tenderness, Swelling' },
  63: { title: 'Open vs Closed Fractures',            topic: 'Bone breaking skin — infection risk' },
  64: { title: 'Splinting Principles',                topic: 'Immobilize one joint above and below' },
  65: { title: 'SAM Splints and Improvised Splints',  topic: 'Sticks, tent poles, foam pads' },
  66: { title: 'Splinting the Ankle',                 topic: 'Most common trail injury' },
  67: { title: 'Splinting the Lower Leg',             topic: 'Tibia/fibula fractures' },
  68: { title: 'Splinting the Knee',                  topic: 'Immobilization and evacuation' },
  69: { title: 'Splinting the Wrist and Hand',        topic: 'Falls, rocks, common kid injuries' },
  70: { title: 'Splinting the Forearm',               topic: 'Ulna/radius fractures' },
  71: { title: 'Sling and Swathe',                    topic: 'Shoulder, upper arm, collarbone' },
  72: { title: 'Clavicle Fractures',                  topic: 'Very common fall injury' },
  73: { title: 'Shoulder Dislocation',                topic: 'Recognition, field reduction debate' },
  74: { title: 'Ankle Sprains vs Fractures',          topic: 'Ottawa Rules simplified' },
  75: { title: 'Knee Injuries',                       topic: 'ACL, meniscus, patellar dislocations' },
  76: { title: 'Hip Fractures',                       topic: 'Elderly and hard fall — evacuation priority' },
  77: { title: 'Femur Fractures',                     topic: 'Life-threatening blood loss potential' },
  78: { title: 'Traction Splinting Basics',           topic: 'Concept and improvised approaches' },
  79: { title: 'Spine Injury Recognition',            topic: 'MOI, tingling, weakness signs' },
  80: { title: 'Spinal Motion Restriction in Field',  topic: 'Cervical collars, log roll' },
  81: { title: 'Head Injuries: Concussion',           topic: 'Symptoms, rest protocol, kids' },
  82: { title: 'Head Injuries: Severe TBI',           topic: 'Unequal pupils, vomiting, LOC' },
  83: { title: 'Rib Fractures',                       topic: 'Breathing pain, flail chest' },
  84: { title: 'Pelvic Fractures',                    topic: 'High-energy trauma, shock risk' },
  85: { title: 'Dislocated Fingers',                  topic: 'Buddy taping, field reduction basics' },
  86: { title: 'Crush Injuries',                      topic: 'Rock falls, rhabdomyolysis risk' },
  87: { title: 'Compartment Syndrome',                topic: 'The 5 Ps — severe limb emergency' },
  88: { title: 'Neurovascular Checks',                topic: 'CMS: Circulation, Motor, Sensation' },
  89: { title: 'Pediatric Bone Differences',          topic: 'Growth plates, greenstick fractures' },
  90: { title: 'Module 3 Review: Trauma Scenario',    topic: 'Fall from height — compound sim' },

  // Module 4: Environmental Emergencies (91-130)
  91:  { title: 'Thermoregulation Basics',            topic: 'How the body manages heat and cold' },
  92:  { title: 'Heat Cramps',                        topic: 'Electrolytes, rest, fluids' },
  93:  { title: 'Heat Exhaustion',                    topic: 'Cool, hydrate, rest, monitor' },
  94:  { title: 'Heat Stroke: Life Threatening',      topic: 'Dry hot skin, confusion — true emergency' },
  95:  { title: 'Cooling Techniques in the Field',    topic: 'Ice packs, evaporative cooling, shade' },
  96:  { title: 'Hydration Strategy on Trail',        topic: 'Kids need more water than adults' },
  97:  { title: 'Hyponatremia: Overhydration',        topic: 'Too much water, low sodium — dangerous' },
  98:  { title: 'Cold Exposure: Stages',              topic: 'Mild, moderate, severe hypothermia' },
  99:  { title: 'Hypothermia Treatment',              topic: 'Gentle rewarming, no vigorous rubbing' },
  100: { title: 'Afterdrop: The Rewarming Danger',    topic: 'Core temp drop after rescue' },
  101: { title: 'Frostbite: Prevention',              topic: 'Layers, moisture, circulation' },
  102: { title: 'Frostbite: Recognition & Treatment', topic: 'Frostnip vs full frostbite' },
  103: { title: 'Immersion Foot (Trench Foot)',       topic: 'Wet cold — river crossings, rain' },
  104: { title: 'Altitude Sickness Overview',         topic: 'AMS, HACE, HAPE explained' },
  105: { title: 'Acute Mountain Sickness',            topic: 'Headache, nausea, fatigue at altitude' },
  106: { title: 'HACE: Brain Swelling',               topic: 'Ataxia, confusion — descend now' },
  107: { title: 'HAPE: Lung Fluid',                   topic: 'Crackles, pink froth — descend now' },
  108: { title: 'Gamow Bags and Descent',             topic: 'Portable hyperbaric treatment' },
  109: { title: 'Lightning Safety',                   topic: 'When to move, 30/30 rule, position' },
  110: { title: 'Lightning Strike Victims',           topic: 'CPR, burns, spinal precautions' },
  111: { title: 'Drowning and Near-Drowning',         topic: 'Airway, rescue breathing, hypothermia' },
  112: { title: 'Water Rescue Safety',                topic: 'Reach, throw, don\'t go — rescuer safety' },
  113: { title: 'Sun and UV Protection',              topic: 'SPF, UPF, time of day, kids\' skin' },
  114: { title: 'Snow Blindness',                     topic: 'UV corneal burn — goggles matter' },
  115: { title: 'Wind Chill and Real Feel',           topic: 'Charts, clothing layers, exposed skin' },
  116: { title: 'Radiation Burns from Reflection',    topic: 'Snow and water amplify UV' },
  117: { title: 'Dehydration Recognition',            topic: 'Urine color, headache, dark eyes' },
  118: { title: 'Electrolyte Balance',                topic: 'Sodium, potassium, magnesium on trail' },
  119: { title: 'Sweat Rate and Fluid Needs',         topic: 'Calculating hydration by activity' },
  120: { title: 'Rain and Cold Rain Dangers',         topic: 'Faster cooling than dry cold' },
  121: { title: 'River Crossing Safety',              topic: 'Reading current, foot placement, kids' },
  122: { title: 'Flash Flood Awareness',              topic: 'Reading terrain, escape routes' },
  123: { title: 'Canyon Hazards',                     topic: 'Slot canyons, rising water, escape' },
  124: { title: 'Desert Heat Survival',               topic: 'Timing, shade, clothing color' },
  125: { title: 'Desert Night Cold',                  topic: 'Temp swings in arid climates' },
  126: { title: 'Wildfire Smoke Inhalation',          topic: 'Masks, evacuation, lung protection' },
  127: { title: 'Carbon Monoxide in Tents',           topic: 'Stoves, generator dangers, symptoms' },
  128: { title: 'Avalanche Basics',                   topic: 'Terrain, beacon, shovel, probe' },
  129: { title: 'Avalanche Burial Response',          topic: 'Organized search, patient airway' },
  130: { title: 'Module 4 Review: Env Scenarios',     topic: 'Heat stroke hiker — decision sim' },

  // Module 5: Navigation & Rescue (131-160)
  131: { title: 'Map Reading Basics',                 topic: 'Topographic maps, contour lines' },
  132: { title: 'Compass Fundamentals',               topic: 'Declination, bearings, orienting' },
  133: { title: 'GPS Devices for Hikers',             topic: 'Garmin, phone GPS, satellite backups' },
  134: { title: 'Satellite Communicators',            topic: 'Garmin inReach, SPOT, Zoleo compared' },
  135: { title: 'Whistle Signals',                    topic: '3 blasts = distress — international code' },
  136: { title: 'Mirror Signaling',                   topic: 'Heliograph technique for aircraft' },
  137: { title: 'Ground-to-Air Signals',              topic: 'Rock, log, debris patterns for rescue' },
  138: { title: 'Signal Fires',                       topic: 'Smoke by day, flame by night' },
  139: { title: 'Calling 911 from the Backcountry',  topic: 'What info to give, GPS coordinates' },
  140: { title: 'SAR: Search and Rescue Teams',       topic: 'How they work, your role, costs' },
  141: { title: 'Heli Rescue Landing Zones',          topic: 'Clearing, size, marking an LZ' },
  142: { title: 'Litter Carries',                     topic: 'Organized evacuation with teams' },
  143: { title: 'Leave a Trip Plan',                  topic: 'Who to tell, what to include' },
  144: { title: 'Night Navigation Basics',            topic: 'Stars, headlamps, pace counting' },
  145: { title: 'Lost Protocol: Stay Put or Go',      topic: 'STOP and when to self-rescue' },
  146: { title: 'Terrain Association',                topic: 'Reading landscape without a map' },
  147: { title: 'Pace Counting',                      topic: 'Measuring distance on trail' },
  148: { title: 'Dead Reckoning',                     topic: 'Track direction + distance = location' },
  149: { title: 'Navigation in Fog and Whiteout',     topic: 'Compass-only movement' },
  150: { title: 'Stream Navigation',                  topic: 'Following water to civilization' },
  151: { title: 'Improvised Compass',                 topic: 'Magnetized needle and leaf' },
  152: { title: 'Sun and Shadow Navigation',          topic: 'Shadow stick method, time of day' },
  153: { title: 'Tree and Moss Navigation Myths',     topic: 'What actually works vs folklore' },
  154: { title: 'Marking a Trail for Rescue',         topic: 'Cairns, flagging, clear path marks' },
  155: { title: 'Preparing Kids for Getting Lost',    topic: 'Hug a tree, whistle, stay visible' },
  156: { title: 'Emergency Bivouac',                  topic: 'Unplanned overnight — priorities' },
  157: { title: 'Water Sources from Map',             topic: 'Blue lines, springs, seasonal streams' },
  158: { title: 'Route Finding on Trail',             topic: 'When trail is unclear or unmarked' },
  159: { title: 'River as Navigation Tool',           topic: 'Upstream vs downstream strategy' },
  160: { title: 'Module 5 Review: Navigation Sim',    topic: 'Off-trail, bad weather scenario' },

  // Module 6: Wilderness Survival (161-200)
  161: { title: 'Survival Priorities: SWOT',          topic: 'Shelter, Water, Ordeal, Tools' },
  162: { title: 'Emergency Shelters',                 topic: 'Debris huts, tarps, bivy sacks' },
  163: { title: 'Hypothermia Prevention Shelter',     topic: 'Insulation from ground up' },
  164: { title: 'Fire Starting Methods',              topic: 'Lighter, ferro rod, bow drill' },
  165: { title: 'Fire in Rain and Wind',              topic: 'Tinder prep, wind blocks' },
  166: { title: 'Safe Fire Management',               topic: 'LNT, fire rings, kid fire safety' },
  167: { title: 'Water Sources in Wild',              topic: 'Streams, dew, plant sources' },
  168: { title: 'Water Purification: Boiling',        topic: 'Rolling boil, altitude adjustment' },
  169: { title: 'Water Filters and Purifiers',        topic: 'Sawyer, Katadyn, SteriPen compared' },
  170: { title: 'Chemical Purification',              topic: 'Iodine tabs, Aquatabs, chlorine drops' },
  171: { title: 'Water from Dangerous Sources',       topic: 'Stagnant, agricultural, chemical risk' },
  172: { title: 'Food in Survival Situations',        topic: 'Caloric needs, short-term fasting' },
  173: { title: 'Foraging Basics: Is It Safe?',       topic: 'Edible vs toxic look-alikes' },
  174: { title: 'Safe Foraging: Berries',             topic: 'Red, blue, white — guidelines' },
  175: { title: 'Safe Foraging: Greens',              topic: 'Dandelion, clover, cattail' },
  176: { title: 'Insects as Food',                    topic: 'Protein source, what to avoid' },
  177: { title: 'Improvised Tools',                   topic: 'Knife, cordage, containers from nature' },
  178: { title: 'Knots Every Hiker Should Know',      topic: 'Bowline, clove hitch, figure eight' },
  179: { title: 'Signaling With Fire',                topic: 'Green wood smoke, 3 fire triangle' },
  180: { title: 'Psychological Survival',             topic: 'Will to live, positive self-talk' },
  181: { title: 'Maintaining Core Temperature',       topic: 'Layering, vapor barriers, priorities' },
  182: { title: 'Halfway Milestone Review',           topic: '182 days — reflect, what you know' },
  183: { title: 'Improvised Rain Collection',         topic: 'Tarps, leaves, funneling rain' },
  184: { title: 'Rocky Terrain Navigation',           topic: 'Ankle safety, scrambling technique' },
  185: { title: 'Snow Melting for Water',             topic: 'Never eat snow raw — body temp cost' },
  186: { title: 'Campsite Selection Safety',          topic: 'Widow-makers, flood zones, wind' },
  187: { title: 'Bear and Wildlife Food Safety',      topic: 'Canisters, hangs, camp hygiene' },
  188: { title: 'Wildlife Encounter Protocol',        topic: 'Bears, cougars, coyotes — what to do' },
  189: { title: 'Improvised Cord and Rope',           topic: 'Bark, plant fiber, paracord uses' },
  190: { title: 'Survival Psychology with Kids',      topic: 'Keeping children calm and engaged' },
  191: { title: 'Making Camp in Emergency',           topic: 'Speed over comfort when light is fading' },
  192: { title: 'Body Heat Sharing',                  topic: 'Huddling, shared sleeping bags' },
  193: { title: 'Improvised Footwear',                topic: 'Protecting feet when boots fail' },
  194: { title: 'Warmth Without Fire',                topic: 'Insulation layering, debris piles' },
  195: { title: 'Reading Cloud Patterns',             topic: 'Incoming weather prediction' },
  196: { title: 'Wind Reading for Shelter',           topic: 'Leeward side, terrain blocking' },
  197: { title: 'Topo Map + Terrain + Survival',      topic: 'Integrated skill use' },
  198: { title: 'Night Survival Priorities',          topic: 'What changes after dark' },
  199: { title: 'Long-Term Wilderness Stay',          topic: 'Resource management, morale' },
  200: { title: 'Module 6 Review: Survival Sim',      topic: 'Lost overnight — full scenario' },

  // Module 7: Kid-Specific (201-240)
  201: { title: 'Child Anatomy Differences',          topic: 'Why kids aren\'t small adults' },
  202: { title: 'Pediatric Vital Signs by Age',       topic: 'Normal ranges for infants to teens' },
  203: { title: 'Infant vs Child vs Adult CPR',       topic: 'Key differences in technique' },
  204: { title: 'Child CPR: Hands-On',               topic: 'Compression depth, rate, two-finger' },
  205: { title: 'Infant Choking Response',            topic: 'Back blows and chest thrusts' },
  206: { title: 'Child Choking Response',             topic: 'Heimlich for kids 1-8 years' },
  207: { title: 'Recognizing Shock in Children',      topic: 'Kids compensate longer — then crash' },
  208: { title: 'Fever in the Wilderness',            topic: 'Measurement, cooling, medication' },
  209: { title: 'Febrile Seizures',                   topic: 'What to do, what not to do' },
  210: { title: 'Allergic Reactions in Kids',         topic: 'Hives, swelling, anaphylaxis signs' },
  211: { title: 'Epinephrine Auto-Injectors',         topic: 'EpiPen use — thigh, hold, don\'t remove' },
  212: { title: 'Asthma on Trail',                    topic: 'Triggers, inhaler use, severe attack' },
  213: { title: 'Stomach Pain in Children',           topic: 'Appendicitis, gas, intussusception' },
  214: { title: 'Diarrhea and Vomiting',              topic: 'Dehydration risk in kids' },
  215: { title: 'Oral Rehydration Therapy',           topic: 'Sugar-salt solution recipe' },
  216: { title: 'Kids and Heat Illness',              topic: 'Why children overheat faster' },
  217: { title: 'Kids and Hypothermia',               topic: 'Greater surface area, faster cooling' },
  218: { title: 'Head Injuries in Children',          topic: 'Pediatric concussion warning signs' },
  219: { title: 'Child Fall Assessment',              topic: 'How high, what surface, LOC?' },
  220: { title: 'Abdominal Trauma in Kids',           topic: 'Spleen and liver vulnerability' },
  221: { title: 'Swallowed Objects',                  topic: 'Coins, berries, batteries — risks' },
  222: { title: 'Plant Ingestion in Kids',            topic: 'Common toxic backyard/trail plants' },
  223: { title: 'Poison Control: Field Use',          topic: '1-800-222-1222 — what to tell them' },
  224: { title: 'Tick Removal in Children',           topic: 'Fine-tipped tweezers, proper angle' },
  225: { title: 'Tick-Borne Illness Signs',           topic: 'Lyme, Rocky Mountain spotted fever' },
  226: { title: 'Bee and Wasp Stings',                topic: 'Remove stinger, cold compress' },
  227: { title: 'Bee Sting Anaphylaxis',              topic: 'EpiPen threshold, call 911' },
  228: { title: 'Rashes: Common Types',               topic: 'Poison ivy, heat rash, friction' },
  229: { title: 'Eye Injuries in Kids',               topic: 'Dirt, twigs, insects — don\'t rub' },
  230: { title: 'Ear Infections on Long Trips',       topic: 'Water in ears, swimmer\'s ear' },
  231: { title: 'Nosebleeds in Children',             topic: 'Lean forward, pinch, how long' },
  232: { title: 'Toothaches in Wilderness',           topic: 'Clove oil, dental wax, pain management' },
  233: { title: 'Anxiety and Fear Responses',         topic: 'Kids in emergencies — calm strategies' },
  234: { title: 'Teaching Kids Basic First Aid',      topic: 'Age-appropriate skills to teach' },
  235: { title: 'Medical ID for Your Child',          topic: 'Bracelets, ICE contacts, allergy cards' },
  236: { title: 'Kid Medications on Trail',           topic: 'Benadryl, ibuprofen, acetaminophen' },
  237: { title: 'Splinting Kids\' Injuries',          topic: 'Smaller limbs, growth plates, padding' },
  238: { title: 'Carrying an Injured Child',          topic: 'Piggyback, improvised carrier' },
  239: { title: 'Mental Health on Long Trips',        topic: 'Keeping kids emotionally regulated' },
  240: { title: 'Module 7 Review: Pediatric Sim',     topic: 'Child falls, allergic reaction scenario' },

  // Module 8: Plants, Animals & Toxins (241-280)
  241: { title: 'Toxicology Basics',                  topic: 'How poisons enter the body' },
  242: { title: 'Snake ID in North America',          topic: 'Rattlesnake, cottonmouth, copperhead' },
  243: { title: 'Snakebite Treatment',                topic: 'Immobilize, don\'t cut/suck, evacuate' },
  244: { title: 'Snakebite Myths Debunked',           topic: 'Tourniquet, suction — why they\'re wrong' },
  245: { title: 'Spider Bites: Brown Recluse',        topic: 'Necrotic wound, slow diagnosis' },
  246: { title: 'Spider Bites: Black Widow',          topic: 'Muscle cramps, systemic reaction' },
  247: { title: 'Scorpion Stings',                    topic: 'Southwest risk, children\'s severity' },
  248: { title: 'Tick Species and Risk',              topic: 'Deer tick vs dog tick, maps' },
  249: { title: 'Lyme Disease Recognition',           topic: 'Bull\'s eye rash, joint pain, fatigue' },
  250: { title: 'RMSF: Rocky Mountain Spotted Fever', topic: 'Rash pattern, rapid progression' },
  251: { title: 'Bee, Wasp, Hornet Differences',      topic: 'Behavior, sting anatomy, risk' },
  252: { title: 'Fire Ant Attacks',                   topic: 'Mound avoidance, mass sting treatment' },
  253: { title: 'Caterpillar and Moth Stings',        topic: 'Urticating hairs, regional species' },
  254: { title: 'Mosquito-Borne Illness',             topic: 'West Nile, Zika — geography matters' },
  255: { title: 'DEET and Permethrin Use',            topic: 'Safe application, clothing treatment' },
  256: { title: 'Poison Ivy, Oak, Sumac',             topic: 'ID, exposure prevention, treatment' },
  257: { title: 'Stinging Nettles',                   topic: 'Immediate treatment, dock leaf myth' },
  258: { title: 'Toxic Plant Ingestion Signs',        topic: 'GI, cardiac, neurological patterns' },
  259: { title: 'Toxic Berries of North America',     topic: 'Pokeweed, nightshade, baneberry' },
  260: { title: 'Toxic Mushrooms',                   topic: 'Amanita, death cap — when to purge' },
  261: { title: 'Plants That Cause Photosensitivity', topic: 'Giant hogweed, wild parsnip burns' },
  262: { title: 'Giardia and Cryptosporidium',        topic: 'Water-borne parasites, symptoms, Tx' },
  263: { title: 'Norovirus in Camps',                 topic: 'Spread, prevention, fluid management' },
  264: { title: 'Rabies Risk and Protocol',           topic: 'Bat exposure, wound washing, PEP' },
  265: { title: 'Animal Bites Treatment',             topic: 'Wound care, tetanus, infection watch' },
  266: { title: 'Porcupine Quills',                   topic: 'Never pull out of pets — kids too' },
  267: { title: 'Jellyfish Stings',                   topic: 'Vinegar rule, tentacle removal' },
  268: { title: 'Sea Urchin Punctures',               topic: 'Spines, infection risk, removal' },
  269: { title: 'Marine Animal Safety',               topic: 'Stingrays, rockfish, cone snails' },
  270: { title: 'Ciguatera and Shellfish Poisoning',  topic: 'Seafood toxins, neurological signs' },
  271: { title: 'Worms and Soil-Borne Parasites',     topic: 'Hookworm, roundworm, prevention' },
  272: { title: 'Hantavirus Risk',                    topic: 'Rodent droppings — ventilation, PPE' },
  273: { title: 'Leptospirosis',                      topic: 'Water contaminated by animal urine' },
  274: { title: 'Plant Allergens on Trail',           topic: 'Pollen, contact, systemic reactions' },
  275: { title: 'Mold and Fungal Exposure',           topic: 'Caves, old cabins, spore inhalation' },
  276: { title: 'Food Poisoning in Camp',             topic: 'Salmonella, E. coli, proper food temps' },
  277: { title: 'Water Source Contamination',         topic: 'Agriculture, mining, fecal — field test' },
  278: { title: 'Improvised Decontamination',         topic: 'Washing chemical exposures in field' },
  279: { title: 'Activated Charcoal Basics',          topic: 'When it helps, when it doesn\'t' },
  280: { title: 'Module 8 Review: Toxin Scenarios',   topic: 'Snakebite + rash + ingestion sim' },

  // Module 9: Body Systems & Illness (281-320)
  281: { title: 'Cardiac Emergencies on Trail',       topic: 'ACS, heart attack recognition' },
  282: { title: 'CPR: Adult Refresher',               topic: 'Chest compressions, 30:2 ratio' },
  283: { title: 'CPR: Single vs Two Rescuer',         topic: 'Switching, fatigue management' },
  284: { title: 'AED Operation',                      topic: 'Turn on, pads, stand clear, shock' },
  285: { title: 'Stroke Recognition',                 topic: 'FAST: Face, Arm, Speech, Time' },
  286: { title: 'Seizures: General Tonic-Clonic',     topic: 'Do not restrain, timing, recovery' },
  287: { title: 'Diabetic Emergencies',               topic: 'Hypoglycemia vs hyperglycemia field' },
  288: { title: 'Asthma Attacks: Severe',             topic: 'Inhaler, positioning, when to evac' },
  289: { title: 'Anaphylaxis Response',               topic: 'EpiPen, antihistamine, lay flat' },
  290: { title: 'Respiratory Emergencies',            topic: 'Pneumothorax, tension pneumo signs' },
  291: { title: 'Shock: Types and Recognition',       topic: 'Hypovolemic, distributive, obstructive' },
  292: { title: 'Treating Shock in Field',            topic: 'Position, fluids, warmth, monitoring' },
  293: { title: 'Abdominal Pain: Appendicitis',       topic: 'McBurney\'s point, rebound tenderness' },
  294: { title: 'Abdominal Pain: Other Causes',       topic: 'Kidney stones, hernia, GI bleed' },
  295: { title: 'Chest Pain Differential',            topic: 'Cardiac, pulmonary, musculoskeletal' },
  296: { title: 'Headache: Serious vs Not',           topic: 'Thunderclap, meningitis, altitude' },
  297: { title: 'Urinary Tract Infection on Trail',   topic: 'Symptoms, hydration, antibiotics' },
  298: { title: 'Respiratory Infections',             topic: 'Pneumonia, bronchitis, when to evac' },
  299: { title: 'GI Illness Management',              topic: 'Rehydration, anti-nausea, safe foods' },
  300: { title: '300 Day Milestone',                  topic: 'Review and celebrate — major milestone' },
  301: { title: 'Dental Emergencies',                 topic: 'Abscess, broken tooth, field pain mgmt' },
  302: { title: 'Eye Infections',                     topic: 'Conjunctivitis, corneal abrasion' },
  303: { title: 'Skin Infections: Cellulitis',        topic: 'Spreading redness, warmth, fever' },
  304: { title: 'Abscesses in the Field',             topic: 'Fluctuance, drainage, packing' },
  305: { title: 'Mental Health Emergencies',          topic: 'Panic attacks, psychosis, overdose' },
  306: { title: 'Altered Mental Status',              topic: 'Differential — AEIOU TIPS mnemonic' },
  307: { title: 'Epistaxis: Severe Nosebleed',        topic: 'When it won\'t stop — packing' },
  308: { title: 'Ear Barotrauma',                     topic: 'Altitude and diving pressure injuries' },
  309: { title: 'Neck Pain: Serious vs Musculoskeletal', topic: 'Red flags, nerve involvement' },
  310: { title: 'Back Pain: Red Flags',               topic: 'Cauda equina, fracture vs muscle' },
  311: { title: 'Pregnancy Emergencies',              topic: 'Ectopic, preterm labor, trauma' },
  312: { title: 'Emergency Childbirth',               topic: 'Basic delivery support if needed' },
  313: { title: 'Menstrual Issues in Field',          topic: 'Heavy bleeding, endometriosis, hygiene' },
  314: { title: 'Fatigue vs Medical Emergency',       topic: 'When tiredness signals something serious' },
  315: { title: 'Nausea Root Causes',                 topic: 'Motion, infection, neurological, toxic' },
  316: { title: 'Medication Side Effects',            topic: 'Common hikers\' meds and interactions' },
  317: { title: 'Pharmacology for Hikers',            topic: 'NSAIDs, antihistamines, antibiotics' },
  318: { title: 'Medical History in Emergencies',     topic: 'Why past medical history changes care' },
  319: { title: 'Mass Casualty Basics',               topic: 'START triage, color system' },
  320: { title: 'Module 9 Review: Medical Sim',       topic: 'Cardiac event on trail — compound sim' },

  // Module 10: Mastery (321-365)
  321: { title: 'Integrating All Modules',            topic: 'How skills connect — the whole picture' },
  322: { title: 'Scenario: Day Hike Gone Wrong',      topic: 'Ankle, heat, lost phone' },
  323: { title: 'Scenario: River Crossing Incident',  topic: 'Drowning near-miss, hypothermia' },
  324: { title: 'Scenario: Lightning Strike',         topic: 'Multi-casualty, trauma, cardiac' },
  325: { title: 'Scenario: Child Snakebite',          topic: 'Identification, treatment, evacuation' },
  326: { title: 'Scenario: Lost at Night',            topic: 'Navigation, signaling, bivouac' },
  327: { title: 'Scenario: Severe Allergic Reaction', topic: 'Anaphylaxis in remote terrain' },
  328: { title: 'Scenario: Camp Fire Accident',       topic: 'Burns, smoke inhalation, triage' },
  329: { title: 'Scenario: Mountain Bike Crash',      topic: 'Head trauma, fractures, road rash' },
  330: { title: 'Scenario: Dehydration Collapse',     topic: 'Heat + dehydration + hyponatremia' },
  331: { title: 'Scenario: Diabetic Emergency',       topic: 'Hypoglycemia, LOC, field management' },
  332: { title: 'Scenario: Rock Fall Injury',         topic: 'Crush, spinal, internal trauma' },
  333: { title: 'Scenario: Wild Animal Encounter',    topic: 'Bite, quills, adrenaline response' },
  334: { title: 'Scenario: Winter Trip Emergency',    topic: 'Hypothermia + frostbite + navigation' },
  335: { title: 'Scenario: Toxic Mushroom Ingestion', topic: 'Amanita, latent onset, evacuation' },
  336: { title: 'Decision Trees: Trauma',             topic: 'Flow chart for all trauma situations' },
  337: { title: 'Decision Trees: Medical',            topic: 'Flow chart for all medical situations' },
  338: { title: 'Decision Trees: Environmental',      topic: 'Flow chart for heat, cold, altitude' },
  339: { title: 'Decision Trees: Pediatric',          topic: 'Flow chart for child-specific emergencies' },
  340: { title: 'Building Your Personal Protocol',    topic: 'Custom plans for your trips' },
  341: { title: 'Pre-Trip Medical Screening',         topic: 'Health check before backcountry' },
  342: { title: 'Building a Custom First Aid Kit',    topic: 'Your kit refined for your risks' },
  343: { title: 'Training Others: Teaching First Aid', topic: 'How to teach your kids and partners' },
  344: { title: 'Simulation Planning',                topic: 'Set up practice drills at home' },
  345: { title: 'Mental Rehearsal Techniques',        topic: 'Visualizing emergency response' },
  346: { title: 'First Aid Certifications to Get',    topic: 'WFA, WFR, CPR — what matters' },
  347: { title: 'Staying Current: Continuing Ed',     topic: 'Refreshers, new guidelines, apps' },
  348: { title: 'Building Situational Awareness',     topic: 'Prevention is the best medicine' },
  349: { title: 'Trail Partner Communication',        topic: 'Expectations, roles, signals' },
  350: { title: 'Family Emergency Plan',              topic: 'At home and on trail — written plans' },
  351: { title: 'Gear Review: Medical Kits',          topic: 'Top field medicine kits compared' },
  352: { title: 'Gear Review: Rescue Tools',          topic: 'SAM splints, tourniquets, signals' },
  353: { title: 'Gear Review: Shelter and Warmth',    topic: 'Emergency bivy, heat blankets' },
  354: { title: 'Gear Review: Navigation Tools',      topic: 'GPS, compass, maps — best options' },
  355: { title: 'Technology in Field Medicine',       topic: 'Apps, AI, satellite comms in emergencies' },
  356: { title: 'Ethics of Wilderness Medicine',      topic: 'Consent, abandonment, limits of care' },
  357: { title: 'When to Refuse Treatment',           topic: 'Patient rights, combative patient' },
  358: { title: 'Rescuer Wellness',                   topic: 'PTSD, critical incident stress' },
  359: { title: 'Lessons from Real Incidents',        topic: 'Case studies from SAR reports' },
  360: { title: 'What You Know vs WFR Level',         topic: 'Honest self-assessment' },
  361: { title: 'Final Review: Trauma Module',        topic: 'Complete trauma competency review' },
  362: { title: 'Final Review: Medical Module',       topic: 'Complete medical competency review' },
  363: { title: 'Final Review: Pediatric & Env',      topic: 'Complete review — kids and environment' },
  364: { title: 'Your Field Medicine Philosophy',     topic: 'Synthesize your year of learning' },
  365: { title: 'Day 365: Field Medic Certified',     topic: 'Graduation — you\'re ready for the trail' },
};

export function getLessonInfo(day) {
  const module = getModuleForDay(day);
  const info = LESSON_TITLES[day] || { title: `Day ${day}`, topic: 'Field Medicine Practice' };
  return { ...info, module, day };
}
